language: node_js
os: linux
dist: xenial
node_js:
  - "14.17.3"
cache:
  directories:
    - ".meteor"
    - ".babel-cache"
script:
  - export TEST_PACKAGES_EXCLUDE="less"
  - export phantom=false
  - travis_retry ./packages/test-in-console/run.sh
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
